
#
# Advanced Digital Signal Processor(?)
#

PRODUCT_PACKAGES += adsp_mdt
PRODUCT_PACKAGES += adsp_b00
PRODUCT_PACKAGES += adsp_b01
PRODUCT_PACKAGES += adsp_b02
PRODUCT_PACKAGES += adsp_b03
PRODUCT_PACKAGES += adsp_b04
PRODUCT_PACKAGES += adsp_b05
PRODUCT_PACKAGES += adsp_b06
PRODUCT_PACKAGES += adsp_b07
PRODUCT_PACKAGES += adsp_b08
PRODUCT_PACKAGES += adsp_b09
PRODUCT_PACKAGES += adsp_b10
PRODUCT_PACKAGES += adsp_b11
